// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwK9wBr23PMM8a0hab8Be7dcrTYsnlcM0',
    appId: '1:795826675643:web:897c934c355fb08be16e9e',
    messagingSenderId: '795826675643',
    projectId: 'aabo-3a729',
    authDomain: 'aabo-3a729.firebaseapp.com',
    storageBucket: 'aabo-3a729.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCD5ObxY41GGJ7ugOpQQZrR6JR61alnASs',
    appId: '1:795826675643:android:b169d9a55c6f9314e16e9e',
    messagingSenderId: '795826675643',
    projectId: 'aabo-3a729',
    storageBucket: 'aabo-3a729.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPlVam1Mi-Mb-AOkbbFBbZQFyxgS-DU_U',
    appId: '1:795826675643:ios:9ae98ea40f0d9f1ce16e9e',
    messagingSenderId: '795826675643',
    projectId: 'aabo-3a729',
    storageBucket: 'aabo-3a729.appspot.com',
    iosClientId: '795826675643-h89pup14ep9n35cbkvdqijbic38p24v0.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseGoogleSignin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPlVam1Mi-Mb-AOkbbFBbZQFyxgS-DU_U',
    appId: '1:795826675643:ios:3050ff06aacfb53de16e9e',
    messagingSenderId: '795826675643',
    projectId: 'aabo-3a729',
    storageBucket: 'aabo-3a729.appspot.com',
    iosClientId: '795826675643-8lr8h3dousqhl8shl65njlnu662328o8.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseGoogleSignin.RunnerTests',
  );
}
